### ISSUE TITLE
Does this support non ascii characters?

### ISSUE THREAD

**Issue by marcqtan** [kineapps/flutter_archive#20]
If the extracted file has a directory and the directory name has a non ascii characters (e.g japanese), it will return the error below during extraction:

```
W/System.err( 7620): java.lang.IllegalArgumentException: MALFORMED[1]
W/System.err( 7620): 	at java.util.zip.ZipCoder.toString(ZipCoder.java:65)
W/System.err( 7620): 	at java.util.zip.ZipFile.getZipEntry(ZipFile.java:626)
W/System.err( 7620): 	at java.util.zip.ZipFile.access$900(ZipFile.java:64)
W/System.err( 7620): 	at java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:584)
W/System.err( 7620): 	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:559)
W/System.err( 7620): 	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:540)
 
```

I can successfully unzip using 7z.

**Comment by marcqtan** [comment]
this is fixed using SHIFT-JIS encoding.
